# Generated by Django 5.2.6 on 2025-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Student Name', max_length=255)),
                ('age', models.IntegerField(help_text='Age', max_length=100)),
                ('dob', models.DateField(help_text='Date of Birth')),
            ],
        ),
    ]
