# Generated by Django 5.2.6 on 2025-09-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Staff Name', max_length=255)),
                ('department', models.CharField(help_text='Department Name', max_length=100)),
                ('doj', models.DateField(help_text='Date of Joining')),
            ],
        ),
    ]
